### ISSUE TITLE
Ping timeout for websocket

### ISSUE THREAD

**Issue by gregorybrad** [burakoner/OKEx.Net#12]
I have code similar to this:

```
var OKexWS = new OkexSocketClient(new Okex.Net.CoreObjects.OkexSocketClientOptions()
            {
                AutoReconnect = true,
                ReconnectInterval=new TimeSpan(0,1,0),
                SocketResponseTimeout= new TimeSpan(0, 0, 30),
                SocketNoDataTimeout = new TimeSpan(0, 0, 30),
            }) ;

var pong = await OKexWS.PingAsync();
```
I am getting a failed pong with the error message of "No response on query received"
From what I can see the requests times out. 

Is this an issue or am I doing something wrong?

**Comment by burakoner** [comment]
There was a little bug in library. I've committed  fixed version both https://github.com/burakoner/OKEx.Net/commit/bc0388c6dce506de3d36fd9bdf9b7c0dd09ac22e and https://www.nuget.org/packages/OKEx.Net/2.0.2.

You can check it out with simple code below

```C#
var ws = new OkexSocketClient();
var ping = ws.Ping();
```

Have a nice day

**Comment by gregorybrad** [comment]
Thank you so much!
