### ISSUE TITLE
Error Code: 3

### ISSUE THREAD

**Issue by miuo** [burakoner/OKEx.Net#2]
When i run this project, in most cases got the error msg:  
{3: Server error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 }

how can i tuning it ?

**Comment by burakoner** [comment]
Can you share your codes with me. Where do you get error?

**Comment by burakoner** [comment]
I think your ISP doesn't allow to connect OKEx

**Comment by miuo** [comment]
Maybe it's due to my internet connect with VPN.
But it's strange that i can connect successfully to huobi by JKorf's Huobi.NET at the same time.
