### ISSUE TITLE
Do you plan to support OKEx unified API v5 ?

### ISSUE THREAD

**Issue by AntiTenzor** [burakoner/OKEx.Net#25]
Hello!

Thank you for a nice library.

At the moment OKEx provides new "unified" API v5.
https://www.okex.com/docs-v5/en/#overview-production-trading-services

Do you plan to support it?
Maybe, as a separate specialized library?

**Comment by ikaman** [comment]
I definitely need this as well. As it seems that you cannot get v3 keys anymore :( so this library wont work for anyone just starting out

**Comment by AntiTenzor** [comment]
> As it seems that you cannot get v3 keys anymore :( so this library wont work for anyone just starting out

OKEx strongly states that they will close v3 API in nearest future (about 2-3 months).
This is what support declares very clearly.
