### ISSUE TITLE
v5 support missing

### ISSUE THREAD

**Issue by ErdincKaragoz** [burakoner/OKEx.Net#27]
Hello,

Since this lib doesn't support v5 and json structures are different, is there a plan to create v5 lib?
Thanks

**Comment by burakoner** [comment]
Bu aralar gerçekten çok yoğunum. Ancak halledeceğim. Çünkü bana da lazım.

**Comment by ErdincKaragoz** [comment]
Kolay gelsin ve tesekkurler cevabiniz icin.
Benim de zamanim pek yok ama ugrasma firsatim olurda yaparsam gonderirim, sira buna gelene kadar muhtmelen birkac ay beklerim sizin yapmanizi :)

**Comment by burakoner** [comment]
Aslında gerçekten çok yoğunum ama senin bu mesajından sonra yazmaya başladım. V5 branch da oluşturdum farkettiysen. Henüz Github'a birşey atmadım ama Rest API'nin yarısını bitirdim. Rest bitince bir versiyon yüklerim websocket sonradan gelir. Tüm yapı tüm endpointler tüm veri yapıları farklı. Bu nedenle sıfırdan bir proje gibi ilerliyor. Eğer eski versiyonu kullanıyorsanız oradaki tüm class lar tüm method imzaları değişiyor maalesef. Çok bekletmeyeceğim. İyi geceler.

**Comment by burakoner** [comment]
I'm working on it

**Comment by burakoner** [comment]
Please take a look for https://github.com/burakoner/OKEx.Net/commit/c53e24f2f10b9005e0e2562f3c53bfe060eceb75
