### ISSUE TITLE
OKEx.NET depends on an older version of CryptoExchange.Net. 

### ISSUE THREAD

**Issue by daniel-levin** [burakoner/OKEx.Net#4]
CryptoExchange.Net does not respect semantic versioning because there are breaking changes from `3.0.5` to `3.0.14`. This renders OKEx.NET unusable if the assembly corresponding to the `3.0.14` NuGet package is loaded, as might happen if one depends also on Binance.NET `6.0.2`.

I am working on updating the package and fixing the breaking changes. I will submit a pull request.

**Comment by burakoner** [comment]
There are some other packages related same dependencies. So I'll update them all. Thank you for feedback

**Comment by burakoner** [comment]
This repository and nuget package have been updated
