### ISSUE TITLE
SubscribeToIndexTickers

### ISSUE THREAD

**Issue by xnlzg** [burakoner/OKEx.Net#42]
SubscribeToIndexTickers 返回的实体对象不对 public virtual CallResult<UpdateSubscription> SubscribeToIndexTickers(string intrumentId, Action<OkexTicker> onData); 应该返回OkexIndexTicker这个吧

**Comment by burakoner** [comment]
Thank you for feed back. Hi. Please take a look to https://www.nuget.org/packages/OKEx.Net/5.1.3 or https://github.com/burakoner/OKEx.Net/commit/1892e867c6e19c0ffaaee244dde35815ce41de3b. It has been fixed.
