### ISSUE TITLE
PlaceOrder 下单都是报错{1: Operation failed. }

### ISSUE THREAD

**Issue by xnlzg** [burakoner/OKEx.Net#45]
OkexClient api = new OkexClient();
api.SetApiCredentials("XXXXXXXX-API-KEY-XXXXXXXX", "XXXXXXXX-API-SECRET-XXXXXXXX", "XXXXXXXX-API-PASSPHRASE-XXXXXXXX");
var trade_01 = api.PlaceOrder("BTC-USDT", OkexTradeMode.Cash, OkexOrderSide.Buy, OkexPositionSide.Long, OkexOrderType.MarketOrder, 0.1m);
用你的demo也是一样

**Comment by xnlzg** [comment]
错误提示不明确。没办法定位

**Comment by alanthinker** [comment]
This can show the error detail info.

**change** 
`if (result.Data.ErrorCode > 0) return WebCallResult<IEnumerable<OkexOrderPlaceResponse>>.CreateErrorResult(result.ResponseStatusCode, result.ResponseHeaders, new ServerError(result.Data.ErrorCode, result.Data.ErrorMessage));`

**to** 
`if (result.Data.ErrorCode > 0) return WebCallResult<IEnumerable<OkexOrderPlaceResponse>>.CreateErrorResult(result.ResponseStatusCode, result.ResponseHeaders, new ServerError(result.Data.ErrorCode, result.Data.ErrorMessage, result.Data.Data));`

**Comment by alanthinker** [comment]
And change OkexPositionSide.Long to OkexPositionSide.Net can fixe the demo error.

**Comment by burakoner** [comment]
Thanks for suggestion. I merged your commit
