### ISSUE TITLE
CryptoExchange.Net updated to version 5.0.0

### ISSUE THREAD

**Issue by Tendx** [burakoner/OKEx.Net#53]
Recently JKorf/CryptoExchange.Net updated to version 5.0.0, and some api interfaces were not adapted.
Can u updated Okex.Net for CryptoExchange.Net 5.0.0 please?

**Comment by xnlzg** [comment]
同求CryptoExchange.Net更新V5

**Comment by mehrdadkhanbani** [comment]
We are still waiting

**Comment by burakoner** [comment]
Here is open source world. I'm vey busy nowadays. If you write codes I'll pull them.

**Comment by burakoner** [comment]
Yes Mr. CEO? Why don't you have any repository?

**Comment by burakoner** [comment]
It's released today https://github.com/burakoner/OKEx.Net/commit/af7dcb3c3074e725e1a337fc73c2b6c3efe4816d
