### ISSUE TITLE
Incorrect URLs for some endpoints

### ISSUE THREAD

**Issue by GeorgeF0** [burakoner/OKEx.Net#54]
Hi! I'm not sure if some endpoints changed their URL at some point, but they now seem to be different than what's in the code. For example:

| Endpoint | Client Code | OKX Documentation |
| :-- | :-- | :-- |
| [Get sub-account balance](https://www.okx.com/docs-v5/en/#rest-api-subaccount-get-sub-account-balance) | api/v5/**users**/subaccount/balances | /api/v5/**account**/subaccount/balances |
| [History of sub-account transfer](https://www.okx.com/docs-v5/en/#rest-api-subaccount-history-of-sub-account-transfer) | api/v5/**users**/subaccount/bills | /api/v5/**asset**/subaccount/bills |
| [Master accounts manage the transfers between sub-accounts](https://www.okx.com/docs-v5/en/#rest-api-subaccount-master-accounts-manage-the-transfers-between-sub-accounts) | api/v5/**users**/subaccount/transfer | /api/v5/**asset**/subaccount/transfer |

There may be others. Requesting these endpoints from the client returns a 404.

**Comment by burakoner** [comment]
Fixed in 5.2.4 and 5.2.5
