### ISSUE TITLE
use demo api

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKEx.Net#56]
I have tried to connect to demo API, but it doesn't work, there is configuration I have to set?

Even i created new API but still i get this error:
50101: Broker id of APIKey does not match current environment.

**Comment by gunduzemreozer** [comment]
You can use with client options as below.

```csharp
OkexClient api = new OkexClient(new Okex.Net.CoreObjects.OkexRestClientOptions
{
    DemoTradingService = true
});
```
