### ISSUE TITLE
Margin Endpoints

### ISSUE THREAD

**Issue by Gustavobbr** [burakoner/OKEx.Net#6]
Hi there,

I saw that the Margin Endpoints are already in OkexClient.cs but not implemented yet.
Is this project still under development and is Margin Endpoints to be implemented ?

Great Work,

Regards,

**Comment by burakoner** [comment]
Not yet.

**Comment by burakoner** [comment]
Okex.Net is now fully featured for Funding, Spot, Algo and Margin API.
