### ISSUE TITLE
Are there plans to add more APIs?

### ISSUE THREAD

**Issue by ChengYen-Tang** [burakoner/OKEx.Net#7]
I cannot find the Perpetual, Futures, Options, Margin API
Is there a chance to add these APIs in the future?

**Comment by burakoner** [comment]
I've some other works in queue. Then I will.

**Comment by ChengYen-Tang** [comment]
Thank you

**Comment by burakoner** [comment]
Okex.Net is now fully featured for Funding, Spot, Algo and Margin API.

**Comment by ChengYen-Tang** [comment]
Thanks

**Comment by ChengYen-Tang** [comment]
@burakoner Can help me make OKEX.NET support Perpetual Swap API?

**Comment by burakoner** [comment]
I am working on it at the moment. I can commit this night late or tomorrow
