### ISSUE TITLE
PlaceAlgoOrder has not trailing stop option

### ISSUE THREAD

**Issue by mo-kml** [burakoner/OKEx.Net#70]
hello friend
the Okex algo order has a algo type called Trailing Stop. but in the nuget this is not available
could you please add this?
thanks

**Comment by mo-kml** [comment]
hello @arashreshadi 
sorry for delay
no i couldn't understand how to do it
if i want to set a trigger order i cant set stop and tp
how could i manage it with one order?
limit order - stop - tp

**Comment by burakoner** [comment]
Fixed in version 5.2.6 
Github Commit: https://github.com/burakoner/OKEx.Net/commit/de2a4cd1b698433cf112177900e68435d9f4484e 
Nuget Package: https://www.nuget.org/packages/OKEx.Net/5.2.6
