### ISSUE TITLE
Error SubscribeToTickersAsync: Deserialize JsonReaderException

### ISSUE THREAD

**Issue by flaxmine9** [burakoner/OKEx.Net#76]
I want to subscribe to tickers (SubscribeToTickersAsync)

var tickers = await okexSocketClient.SubscribeToTickersAsync("ETH-USDT", ticker =>
{
    Console.WriteLine($"Ask price: {ticker.AskPrice}");
});

It gives this error every +-5 seconds:

Error | OKX WS Api | Deserialize JsonReaderException: Unexpected character encountered while parsing value: p. Path '', line 0, position 0., Path: , LineNumber: 0, LinePosition: 0. Data: pong
Warning | OKX WS Api | Socket 1 Message not handled: pong

**Comment by 8perezm** [comment]
Same pong error in https://github.com/burakoner/OKEx.Net/issues/41 which was closed.  I have the same problem.

**Comment by overstartup** [comment]
i have the same issue, too.

**Comment by burakoner** [comment]
CryptoExchange.Net causes this problem. CryptoExchange.Net accepts json text for response, but OKX sends only "pong" and this causes an error. I wrote to JKorf 3-4 times for this problem with my solution offer, I created merge requests but no-sense. 
If there will be any progress I'll fix it.
