### ISSUE TITLE
Unknown error in PlaceAlgoOrder 

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKEx.Net#78]
I want to set a stop lost and take profit by PlaceAlgoOrder, but it returns -1 error without any message.

my code:
```
    var StopProfitResult1 = api.PlaceAlgoOrder(preOrder.Symbol, trademode, orderSide, OkexAlgoOrderType.OCO, preOrder.Quantity,
                                                 positionSide: positionSide, slOrderPrice: -1, slTriggerPrice: preOrder.StopLostPrice,
                                                 tpOrderPrice: -1, tpTriggerPrice: preOrder.TakeProfitPrice);
```

StopProfitResult1.RequestBody:

`{"instId":"SOL-USDT-SWAP","ordType":"oco","posSide":"long","side":"sell","slOrdPx":"-1","slTriggerPx":"14.3506904678614","sz":"10","tdMode":"cross","tpOrdPx":"-1","tpTriggerPx":"14.8679285964158"}`

**Comment by arashreshadi** [comment]
Me too, 
 api.PlaceAlgoOrder(
                "XRP-USDT-SWAP", 
                OkexTradeMode.Isolated, 
                OkexOrderSide.Buy, 
                OkexAlgoOrderType.OCO,
                200, 
                null,
                false,
                OkexPositionSide.Long, 
                null, 
                OkexAlgoPriceType.Last, 
                0.24m, 
                0.25m, 
                OkexAlgoPriceType.Last,
                0.10m, 
                0.10m,
                0.18m, 
                0.18m
                );
