### ISSUE TITLE
Please update CryptoExchange.Net up to version 5.3.0

### ISSUE THREAD

**Issue by wecando168** [burakoner/OKEx.Net#85]
Please update CryptoExchange.Net up to version 5.3.0 ,TKS!

**Comment by burakoner** [comment]
Version 5.3.0 is released with this commit https://github.com/burakoner/OKEx.Net/commit/1700b679454393180777e3a9eb06772ed0a2d159 
Also nuget package is available on https://www.nuget.org/packages/OKEx.Net/5.3.0
