### ISSUE TITLE
How to use stoploss and take profit?

### ISSUE THREAD

**Issue by mytran1998** [burakoner/OKEx.Net#86]
Hey bro, I have a question need support of you.

I want create order have stop loss and take profit. I use PlaceAlgoOrder but it wrong.
You can help me a code example? Thanks very much :)

**Comment by arashreshadi** [comment]
any luck?

**Comment by mytran1998** [comment]
No, I dont create it

**Comment by arashreshadi** [comment]
I have done it with the pure HttpWebRequest, and use the okex.net for subscibing the channels

**Comment by overstartup** [comment]
it just works in one side. You can use "OkexAlgoOrderType.Conditional" but it just triggers stop lost. it is better to send auto trigger in your code and active the profit.
```
          StopProfitResult = api.PlaceAlgoOrder(preOrder.Symbol, trademode, orderSide, OkexAlgoOrderType.Conditional,
                      preOrder.Quantity, positionSide: positionSide, slOrderPrice: -1, slTriggerPrice: preOrder.StopLostPrice);
```
