### ISSUE TITLE
error in calling UnitConvert

### ISSUE THREAD

**Issue by overstartup** [burakoner/OKEx.Net#88]
```
 var r=   api.UnitConvert(OkexConvertType.CurrencyToContract, OkexConvertUnit.Usdt,  Symbol,  Price,  OrderSizeUsdt);
            decimal size = r.Data.Size;
```
Could you please check this method? 
it has error.
{51000: Parameter unit  error }

**Comment by burakoner** [comment]
`api.UnitConvert(OkexConvertType.CurrencyToContract, instrumentId: "BTC-USD-SWAP", price: 35000, size: 0.888m);`
This works perfect. Can you share your parameters please.
