### ISSUE TITLE
Deserialize JsonSerializationException in OkexFundingAssetInformation

### ISSUE THREAD

**Issue by EgorovOleg** [burakoner/OKEx.Net#9]
Hi i got an error in the Funding_GetAllCurrencies_Async function "Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path '[25].min_withdrawal', line 1, position 3003." Decision this problem is to make a nullable decimal in the "MinWithdrawalAmount" property.

**Comment by burakoner** [comment]
Yes you're right. I'm updating in a few minutes.

**Comment by burakoner** [comment]
Version 1.5.7 is released on both github and nuget

**Comment by EgorovOleg** [comment]
Thank you
