### ISSUE TITLE
Could you please add a new api: /api/v5/market/exchange-rate

### ISSUE THREAD

**Issue by wangmos** [burakoner/OKEx.Net#91]
i need this api to work, thank you!

**Comment by burakoner** [comment]
OK. I'm adding now. You'll see in next release

**Comment by burakoner** [comment]
You can check it on https://github.com/burakoner/OKEx.Net/commit/6ded6f9fb9efd5b21f742223fb3efc9e903827e3 commit and https://www.nuget.org/packages/OKEx.Net/5.3.1 release
