### ISSUE TITLE
Missing params in Place Order

### ISSUE THREAD

**Issue by pepakko** [burakoner/OKEx.Net#92]
Hello! Looks like there's some missing params in [PlaceOrder](https://www.okx.com/docs-v5/en/#rest-api-trade-place-order) function, like tp/sl among others.
Have you in mind to update this function with the API params? Thank you!

**Comment by burakoner** [comment]
I've added missing 8 params in placing orders. I'll release new version this evening. Thanks for feedback

**Comment by burakoner** [comment]
Version 5.3.3 released https://github.com/burakoner/OKEx.Net/commit/d8e82c16220fca579e90f58faab881f7e991965c https://www.nuget.org/packages/OKEx.Net/5.3.3
