### ISSUE TITLE
Spot -> Market Emir Hatası

### ISSUE THREAD

**Issue by emin-karadag** [burakoner/OKEx.Net#94]
Merhabalar,
OKEx.Net -> v5.3.1 kullanıyorum.

`PlaceOrderAsync()` metodunu kullanarak başarılı bir şekilde LIMIT emir gönderebiliyorum. Ancak MARKET emir göndermeyi bir türlü başaramadım. Aşağıya örnek bir API isteği ve o isteğin sonucunu paylaşıyorum.

**NOT:** Benzer şekilde `PlaceMultipleOrdersAsync()` için de geçerli. Çoklu MARKET emir de gönderemedim.

**Örnek Market Emir Sorgusu:**
`await client.PlaceOrderAsync("BTC-USDT", OkexTradeMode.Cash, OkexOrderSide.Buy, OkexPositionSide.Net, OkexOrderType.MarketOrder, 0.00002M, ct);`

**Bu sorgunun sonucu aşağıdaki gibidir:**
Error Code: 1,
Error Message: All operations failed

**Yukarıdaki sorgu için:**
RequestUrl: [https://www.okx.com/api/v5/trade/order](https://www.okx.com/api/v5/trade/order)
RequestBody: `{"instId":"BTC-USDT","ordType":"market","posSide":"net","side":"buy","sz":"0.00002","tag":"538a3965e538BCDE","tdMode":"cash"}`

Bu konuda yardımlarınızı bekliyorum, şimdiden teşekkürler.

**Comment by burakoner** [comment]
Ancak bir geliştirme daha yaptım dün. Bununla senin karşılaştığın problemde sorunun ne olduğunun bilgisini result.Data içindeki her bir emir sonucu içinde artık tam olarak görebileceksin.

**Comment by emin-karadag** [comment]
Teşekkür ederim bilgilendirme için.
