### ISSUE TITLE
How can I calculate withdrawal fee automatically?

### ISSUE THREAD

**Issue by sabond9** [burakoner/OKEx.Net#96]
Hello. I need to calculate withdrawal fee automatically in Funding. Okex fee has different value depend on token and network type. Put it each time manually isn't good solution. Following this code we need to put it manually:
`var funding_09 = api.Withdraw("USDT", 100.0m, OkexWithdrawalDestination.DigitalCurrencyAddress, "toAddress", "password", 1.0m, "USDT-TRC20");`

Please provide some solutions

**Comment by burakoner** [comment]
You'll define fee amount in new endpoint
https://www.okx.com/docs-v5/en/#rest-api-funding-withdrawal

**Comment by burakoner** [comment]
This is blockchain. You always have to define fee. I recommend you to find average withdrawal fees for each asset. OKX maybe share this kind of data. If I found I'll share with you.

**Comment by burakoner** [comment]
check this out
https://www.okx.com/docs-v5/en/#rest-api-funding-get-currencies
