### ISSUE TITLE
What password do I need to use?

### ISSUE THREAD

**Issue by sabond9** [burakoner/OKEx.Net#97]
Please explain what password do I need to pass through parameters here:
`var funding_09 = api.Withdraw("USDT", 100.0m, OkexWithdrawalDestination.DigitalCurrencyAddress, "toAddress", "password", 1.0m, "USDT-TRC20");`

**Comment by burakoner** [comment]
It's not login password, it's Trade Password. When I looked at api docs again I dont see any password parameter. THis endpoint has been changed. I'll implement it in this week

![Screenshot_2](https://user-images.githubusercontent.com/21169085/235740632-14efb8a4-12c4-4a51-ba53-f23a9fabaa9f.png)

**Comment by burakoner** [comment]
Fixed in https://github.com/burakoner/OKEx.Net/commit/5c5e7a8bfa488407ee94e70570e6a79dc5231e2d and https://www.nuget.org/packages/OKEx.Net/5.3.4
